### PR TITLE
Hi Tao, I spend some time and implemented shadowsocks multiport configuration

### PR DESCRIPTION
**Pull request by vmlinz**
@ftao 
# Added variables

* port_password, used to configure port_password manually 
* shadowsocks_enable_multiport, enable multiple port config, only possible for python
* shadowsocks_enable_multiport_auto_config, enable automactic random config for multiple port
* timeout, used to specify shadowsocks timeout

# Added a python script to generate random port and password pairs

# Both manual and automatic configuration works on my laptop

# Issues

* The python script should be written to a one line script so we can remove the file
* The port_password receives raw json string, maybe we should use yaml dict then template it using jinja2

### CODE REVIEW

**Comment by vmlinz** [comment]
Refer to https://github.com/shadowsocks/shadowsocks/wiki/Configure-Multiple-Users

**Comment by ftao** [comment]
> The port_password receives raw json string, maybe we should use yaml dict then template it using jinja2
I agree , raw json string is hard to write . 

Regarding the python script ,  I think we can make it template with custome filter, something like that .  
```
{% if shadowsocks_enable_multiport_auto_config %}
  "port_password" : {
        {% for port in range(port_start, port_end) %}
        "{{ port }}" :   "{{ lookup('password',  'cred/ss-password/{{ port }}.txt') }}"  {% if not loop.last %}, {% endif %}
  }
{% else %}
```

**Comment by ftao** [comment]
@vmlinz 
And there are  to_json filter ,  so we could   define by yaml dict  and convert it to json to in template .

**Comment by vmlinz** [comment]
@ftao 

* for the manual configuration, I will convert the json string to yaml dict, thanks for the json filter.
* for the automatic configuration, I am trying to deploy a shadowsocks multiport server without any mannual configuration, I will use a django/rails app to manage these configurations. The random passwords are intended, client users will receive their own configuration by mail or through a web app.
* About the password lookup, I will read the documentation and we can discuss for the details 

Thanks

**Comment by ftao** [comment]
但是你每次跑playbook 都会生成不同的密码， 难道每次跑过， 都重新通知一遍用户？

**Comment by vmlinz** [comment]
@ftao 我之前的想法是每次play之后服务器上的配置监控程序会通知后端程序配置变更，用户从定制的客户端里面看不到这一层信息。不过你说的也很对，没有必要每次都重新生成密码，我去看看你提到的password lookup。

现在手工输入这边的配置变量是yaml的dict了。

我再想想多端口这边的逻辑，谢谢你提到的那个，我看看能不能解决我的问题。

**Comment by vmlinz** [comment]
Current issues:

* how to deal the random port passwords pairs generation with consideration of keep the last time configurations. 

Possible solutions:

* Using password lookup , saving the port passwords for different host int different files once generated.
* Separate the password generation and the ansible play, use script to generate host variables then provide them to ansible as external variables.

@ftao How do you think?

**Comment by ftao** [comment]
@vmlinz   I thinks It's a good idea to  separate the two step,  make the config more clean .

**Comment by vmlinz** [comment]
@ftao Indeed! If variables are provided from files, then there's no need to distinguish manual from auto config. They are just different ways of providing variables.

I'm checking https://docs.ansible.com/ansible/include_vars_module.html. I will send further commits once finished, please help review it.

Thanks

**Comment by vmlinz** [comment]
I was about to make the solution overly complicated.

The discussed solution is just much simpler and much cleaner.

**Comment by vmlinz** [comment]
@ftao Now it looks simple and clean, port_password will have to be provided by the user no matter how he creates the port and password pairs.

Please help review it.

**Comment by ftao** [comment]
Cool,  merged .

**Pull request merged**
